### ISSUE TITLE
unicode decode error

### ISSUE THREAD

**Issue by LSYS** [soodoku/clean-names#3]
![IMG_20200924_222748](https://user-images.githubusercontent.com/10510571/94881707-ae417e80-0498-11eb-9661-7f543e034390.jpg)

error when running process_names.py

**Comment by LSYS** [comment]
setting encoding to utf-8 in lines 17 and 21 solves the issue (from @soodoku )

**Comment by soodoku** [comment]
yup. can you do a PR for this?
