### ISSUE TITLE
seat column error in process_names.py

### ISSUE THREAD

**Issue by LSYS** [soodoku/clean-names#5]
was testing out process_names.py using a minimal csv with a single column as `Name`. Got this error because my csv does not contain a `seat` column.

```
Traceback (most recent call last):
  File "process_names.py", line 45, in <module>
    args.all)
  File "D:\who\search-names-master\clean_names\names.py", line 107, in process_name_list
    r['seat'].strip()))
KeyError: 'seat'
```

commenting out `lines 106-107` and it runs smoothly as expected

**Comment by soodoku** [comment]
@LSYS: this isn't a bug per se but @suriyan we can treat it as such and support running the script without the seat
